# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOIUVHpQnIUeuVw8nYaDHR5QnNX7S9wM
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("fdfffd.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("hrrhrhrtrthezdrh.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("hrrhdhdr.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rgzd.jfif")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)